/* NILE RUSH service worker — offline play. The PRECACHE list and VERSION are generated by `npm run build:sw`. */
const VERSION = 'nile-rush-16d3b42d63';
const PRECACHE = /*PRECACHE_START*/[
  "./",
  "assets/assets.json",
  "icons/apple-touch-icon.png",
  "icons/favicon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "manifest.json",
  "src/assets/AssetManager.js",
  "src/audio/AudioEngine.js",
  "src/audio/Music.js",
  "src/audio/Sfx.js",
  "src/characters/CharacterData.js",
  "src/characters/CharacterView.js",
  "src/core/Config.js",
  "src/core/EventBus.js",
  "src/core/Pool.js",
  "src/core/Utils.js",
  "src/core/mat4.js",
  "src/game/CameraRig.js",
  "src/game/Game.js",
  "src/game/Run.js",
  "src/input/InputManager.js",
  "src/main.js",
  "src/missions/Achievements.js",
  "src/missions/Missions.js",
  "src/particles/ParticleSystem.js",
  "src/player/Player.js",
  "src/rendering/Camera.js",
  "src/rendering/GLTFLoader.js",
  "src/rendering/Geometry.js",
  "src/rendering/Renderer.js",
  "src/rendering/Shaders.js",
  "src/storage/SaveManager.js",
  "src/ui/Hud.js",
  "src/ui/UI.js",
  "src/ui/icons.js",
  "src/ui/logo.js",
  "src/ui/screens/Panels.js",
  "src/ui/style.css",
  "src/world/Collectibles.js",
  "src/world/EnvBuilders.js",
  "src/world/Environments.js",
  "src/world/Obstacles.js",
  "src/world/Patterns.js",
  "src/world/Props.js",
  "src/world/SignAtlas.js",
  "src/world/Spawner.js",
  "src/world/TimeOfDay.js",
  "src/world/World.js"
]/*PRECACHE_END*/;

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(VERSION).then((cache) => Promise.all(PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' })).catch(() => null)))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('nile-rush-') && k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  // page navigations: network first, fall back to the cached shell when offline
  if (req.mode === 'navigate') {
    event.respondWith(fetch(req).then((res) => { const copy = res.clone(); caches.open(VERSION).then((c) => c.put('index.html', copy)); return res; }).catch(() => caches.match('index.html').then((r) => r || caches.match('./'))));
    return;
  }
  // everything else: cache first, refresh in the background (stale-while-revalidate)
  event.respondWith(caches.open(VERSION).then((cache) => cache.match(req).then((hit) => {
    const net = fetch(req).then((res) => { if (res && res.ok) cache.put(req, res.clone()); return res; }).catch(() => hit);
    return hit || net;
  })));
});
